#!/bin/bash
set -euo pipefail

external_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../" && pwd)"

# Required so the host binaries can find shared libraries they need:
[ -d "${external_dir}/ubuntu-22.04-x86_64-native/host-libs" ] && \
    export LD_LIBRARY_PATH="${external_dir}/ubuntu-22.04-x86_64-native/host-libs"

exec "${external_dir}/ubuntu-22.04-x86_64-native/usr/bin/x86_64-linux-gnu-gcc-ar-12" "$@"
