"""aarch64-linux-gnu gcc 11 toolchains for Bazel."""

module(
    name = "aarch64_linux_gnu",
    version = "0.0.0",
    bazel_compatibility = [">=7.7.1"],
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

toolchains = use_extension("//:extensions.bzl", "toolchains")
use_repo(
    toolchains,
    "linux-libc-5.15.0-aarch64",
    "linux-libc-5.15.0-aarch64-cross",
    "linux-libc-5.15.0-x86_64",
    "linux-libc-5.4.0-aarch64",
    "linux-libc-5.4.0-aarch64-cross",
    "ubuntu-22.04-aarch64-native",
    "ubuntu-22.04-arm64-cross",
    "ubuntu-22.04-x86_64-native",
)

# Register the Jetpack toolchains first, so bazel chooses them over the generic ones.
register_toolchains(
    "//toolchain:jp512_linux_x86_64",
    "//toolchain:jp62_linux_x86_64",
    "//toolchain:jp512_linux_aarch64",
)

register_toolchains(
    "//toolchain:aarch64_linux_x86_64",
    "//toolchain:native_linux_aarch64",
    "//toolchain:native_linux_x86_64",
)
