load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello_c",
    srcs = ["hello.c"],
)

cc_binary(
    name = "hello_cc",
    srcs = ["hello.cc"],
)
